[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 57600
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_A0:85:E3:F0:A4:0C-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_A0:85:E3:F0:A4:0C-if00
targets = upload, monitor
build_flags = 
   -D CORE_DEBUG_LEVEL=3
   -D ARDUINO_USB_CDC_ON_BOOT=1

# old waveshare esp display device
