[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 57600
upload_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_9C:13:9E:F2:5F:64-if00
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_9C:13:9E:F2:5F:64-if00
targets = upload, monitor
build_flags = 
   -D CORE_DEBUG_LEVEL=3
   -D ARDUINO_USB_CDC_ON_BOOT=1
   -D BOARD_HAS_PSRAM

# esp32-s3 super mini settings
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

# other pairing device, esp32-s3 super mini
